# Generated by Django 5.2.14 on 2026-05-07 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.DecimalField(decimal_places=3, help_text='Segundos, reps ou kg conforme a prova', max_digits=12, verbose_name='valor bruto')),
                ('tiebreak', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='tie-break')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='posição calculada')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='pontos ganhos')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='athletes.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event', verbose_name='prova')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='athletes.team')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['event', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ResultAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(help_text='Campos antes da edição ou diff')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='scores.result')),
            ],
            options={
                'verbose_name': 'Auditoria de resultado',
                'verbose_name_plural': 'Auditorias de resultados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('seconds', 'Tempo (segundos)'), ('reps', 'Repetições'), ('kg', 'Quilogramas'), ('points', 'Pontos')], default='seconds', max_length=20, verbose_name='métrica')),
                ('lower_is_better', models.BooleanField(default=True, help_text='For Time: sim; AMRAP/Reps/Máx: não', verbose_name='menor valor é melhor')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_config', to='events.event', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'Configuração de pontuação',
                'verbose_name_plural': 'Configurações de pontuação',
            },
        ),
        migrations.CreateModel(
            name='PointsTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='posição (1 = primeiro)')),
                ('points', models.PositiveIntegerField(verbose_name='pontos')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_table', to='events.event', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'Entrada da tabela de pontos',
                'verbose_name_plural': 'Tabela de pontos',
                'ordering': ['event', 'position'],
                'constraints': [models.UniqueConstraint(fields=('event', 'position'), name='scores_pointstableentry_event_position_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('athlete__isnull', False), ('team__isnull', True)), models.Q(('athlete__isnull', True), ('team__isnull', False)), _connector='OR'), name='result_athlete_xor_team'),
        ),
    ]
