# Generated by Django 5.2.14 on 2026-05-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_championship_flexible'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstableentry',
            options={'ordering': ['event', 'category', 'position'], 'verbose_name': 'Entrada da tabela de pontos', 'verbose_name_plural': 'Tabela de pontos'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['event', 'position'], 'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.RemoveConstraint(
            model_name='pointstableentry',
            name='scores_pointstableentry_event_position_uniq',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='rank',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='raw_value',
            new_name='raw_score',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='tiebreak',
            new_name='tiebreak_score',
        ),
        migrations.AddField(
            model_name='pointstableentry',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Vazio = mesma tabela para todas as categorias.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='events.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='scoreconfig',
            name='lower_is_better',
            field=models.BooleanField(default=True, help_text='Sincronizado com Event.score_mode quando possível.', verbose_name='menor valor é melhor'),
        ),
        migrations.AddConstraint(
            model_name='pointstableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('event', 'position'), name='scores_pts_event_pos_global'),
        ),
        migrations.AddConstraint(
            model_name='pointstableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('event', 'category', 'position'), name='scores_pts_event_cat_pos'),
        ),
    ]
