# Generated by Django 5.2.14 on 2026-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_championship_flexible'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='position_override',
            field=models.PositiveIntegerField(blank=True, help_text='Se preenchido, substitui a posição calculada automaticamente.', null=True, verbose_name='posição manual (desempate)'),
        ),
        migrations.AlterField(
            model_name='scoreconfig',
            name='metric',
            field=models.CharField(choices=[('seconds', 'Tempo (segundos/minutos)'), ('reps', 'Repetições'), ('rounds_reps', 'Rounds + repetições'), ('kg', 'Carga (kg/lb)'), ('points', 'Pontos diretos')], default='seconds', max_length=20, verbose_name='métrica'),
        ),
    ]
