# Generated by Django 5.2.14 on 2026-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_championship_flexible'),
        ('events', '0005_performance_indexes'),
        ('scores', '0003_leaderboard_improvements'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['event'], name='scores_result_event_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['athlete'], name='scores_result_athlete_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['team'], name='scores_result_team_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['event', 'position'], name='scores_result_event_pos_idx'),
        ),
    ]
