# Generated by Django 5.2.14 on 2026-05-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nome')),
                ('start_date', models.DateField(verbose_name='data início')),
                ('end_date', models.DateField(verbose_name='data fim')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='competição atual')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitions/logos/', verbose_name='logo')),
                ('active_categories', models.JSONField(default=list, help_text='Ex: ["Rx", "Scaled", "Masters", "Team"]', verbose_name='categorias ativas')),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('event_type', models.CharField(choices=[('for_time', 'For Time'), ('amrap', 'AMRAP'), ('max_load', 'Max Load'), ('tiebreak', 'Tiebreak')], default='for_time', max_length=20, verbose_name='tipo')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='data e hora')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='local/estação')),
                ('eligible_category', models.CharField(default='Rx', max_length=20, verbose_name='categoria elegível')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.competition', verbose_name='competição')),
            ],
            options={
                'verbose_name': 'Prova (WOD)',
                'verbose_name_plural': 'Provas (WODs)',
                'ordering': ['competition', 'display_order', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.PositiveIntegerField(default=1, verbose_name='número do heat')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='horário previsto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluído')], default='pending', max_length=20, verbose_name='status')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_schedules', to='athletes.athlete', verbose_name='atleta')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='events.event', verbose_name='prova')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_schedules', to='athletes.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'Heat (cronograma)',
                'verbose_name_plural': 'Heats (cronograma)',
                'ordering': ['event', 'heat_number', 'scheduled_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('athlete__isnull', False), ('team__isnull', True)), models.Q(('athlete__isnull', True), ('team__isnull', False)), _connector='OR'), name='heat_athlete_xor_team')],
            },
        ),
    ]
