# Generated by Django 5.2.14 on 2026-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_default_division_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='heatschedule',
            options={'ordering': ['event', 'heat_number', 'lane_number', 'scheduled_time'], 'verbose_name': 'Heat (cronograma)', 'verbose_name_plural': 'Heats (cronograma)'},
        ),
        migrations.AddField(
            model_name='event',
            name='metric_type',
            field=models.CharField(blank=True, choices=[('seconds', 'Tempo'), ('reps', 'Repetições'), ('rounds_reps', 'Rounds + reps'), ('kg', 'Carga'), ('points', 'Pontos')], default='seconds', max_length=20, verbose_name='tipo de métrica'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_aggregate_method',
            field=models.CharField(choices=[('sum', 'Soma dos atletas'), ('average', 'Média dos atletas'), ('best', 'Melhor resultado do time'), ('manual', 'Admin define manualmente')], default='sum', max_length=12, verbose_name='agregação do time'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_scoring_format',
            field=models.CharField(choices=[('joint', 'Pontuação conjunta (um resultado para o time)'), ('individual', 'Cada atleta pontua; time agrega depois')], default='joint', help_text='Conjunta: um lançamento por time. Individual: cada atleta + agregação.', max_length=12, verbose_name='formato em provas de time'),
        ),
        migrations.AddField(
            model_name='heatschedule',
            name='lane_number',
            field=models.PositiveIntegerField(default=1, verbose_name='raia'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='mode',
            field=models.CharField(choices=[('individual', 'Individual (por categoria)'), ('team', 'Times (ranking único)'), ('mixed', 'Individual e times (ambos)')], default='individual', max_length=20, verbose_name='modalidade'),
        ),
        migrations.AlterField(
            model_name='heatschedule',
            name='heat_number',
            field=models.PositiveIntegerField(default=1, verbose_name='número do heat / bateria'),
        ),
    ]
