# Generated by Django 5.2.14 on 2026-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_championship_flexible'),
        ('events', '0004_leaderboard_improvements'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='heatschedule',
            index=models.Index(fields=['event'], name='events_heat_event_idx'),
        ),
        migrations.AddIndex(
            model_name='heatschedule',
            index=models.Index(fields=['event', 'status'], name='events_heat_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='heatschedule',
            index=models.Index(fields=['event', 'heat_number'], name='events_heat_event_num_idx'),
        ),
    ]
