# Generated by Django 5.2.14 on 2026-05-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('category', models.CharField(choices=[('Team', 'Team')], default='Team', max_length=20, verbose_name='categoria (equipes)')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('nickname', models.CharField(blank=True, max_length=120, verbose_name='apelido')),
                ('category', models.CharField(choices=[('Rx', 'Rx'), ('Scaled', 'Scaled'), ('Masters', 'Masters')], default='Rx', max_length=20, verbose_name='categoria')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='gênero')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/photos/', verbose_name='foto')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='athletes.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['name'],
            },
        ),
    ]
